import { GoogleGenAI } from "@google/genai";

export async function transformProductPhoto(base64Image: string, mimeType: string) {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image.split(',')[1], // Remove the data:image/png;base64, prefix
            mimeType: mimeType,
          },
        },
        {
          text: 'Transform this product photo into a professional studio shot. Place the product on a clean, pure white background. Ensure the lighting is soft and professional, highlighting the product details. The final image should look like it was taken in a professional photography studio for an e-commerce website.',
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image generated by the model.");
}
